/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetAllPaymentSourcesResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type GetAllPaymentSourcesResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/paymentsources
 */
export interface PaymentsourcesRequestBuilder extends BaseRequestBuilder<PaymentsourcesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetAllPaymentSourcesResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetAllPaymentSourcesResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PaymentsourcesRequestBuilderUriTemplate = "{+baseurl}/api/paymentsources";
/**
 * Metadata for all the requests in the request builder.
 */
export const PaymentsourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PaymentsourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetAllPaymentSourcesResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
