version: '3'

tasks:
  environment:check:
    preconditions:
      - sh: npm --version
        msg: "The npm CLI is required"
    cmds:
      - echo "All frontend tooling is installed"

  install-locked-dependencies:
    cmds:
      - npm ci

  install-dependencies:
    cmds:
      - npm install

  build:
    cmds:
      - npm run build

  build:production:
    cmds:
      - npm run build -- --configuration production

  dev:
    cmds:
      - npm run dev

  lint:
    cmds:
      - npm run lint

  test:
    cmds:
      - npm run test

  lint:fix:
    cmds:
      - npm run lint -- --fix

  run:
    cmds:
      - npm run start

  api-client:generate:
    cmds:
      - npm run api-client:generate