version: '3'

includes:
  clients:
    taskfile: clients/Taskfile.yml
    dir: clients

tasks:
  environment:check:
    preconditions:
      - sh: npm --version
        msg: "The npm CLI is required"
    cmds:
      - echo "All frontend tooling is installed"

  install-dependencies:
    cmds:
      - npm install

  build:
    deps:
      - task: clients:build
    cmds:
      - npm run build

  dev:
    cmds:
      - npm run dev

  lint:
    cmds:
      - npm run lint

  lint:fix:
    cmds:
      - npm run lint -- --fix

  run:
    cmds:
      - npm run start