version: '3'

includes:
  backend:
    taskfile: backend/Taskfile.yml
    dir: backend
  frontend:
    taskfile: frontend/Taskfile.yml
    dir: frontend
  host:
    taskfile: host/Taskfile.yml
    dir: host

tasks:
  environment:check:
    deps:
      - task: backend:environment:check

  install-tools:
    cmds:
      - task: restore-dotnet-tools

  install-dependencies:
    deps:
      - task: backend:install-dependencies
      - task: frontend:install-dependencies

  install-locked-dependencies:
    deps:
      - task: backend:install-locked-dependencies
      - task: frontend:install-locked-dependencies

  lint:
    deps:
      - task: backend:lint
      - task: frontend:lint

  lint:fix:
    deps:
      - task: backend:lint:fix
      - task: frontend:lint:fix

  build:
    deps:
      - task: backend:build
      - task: frontend:build

  test:
    deps:
      - task: backend:test

  run:
    deps:
      - task: backend:api:run
      - task: frontend:run

  restore-dotnet-tools:
    cmds:
      - dotnet tool restore

  image:build:
    vars:
      TAG: '{{.TAG | default "latest"}}'
      REPOSITORY: '{{.REPOSITORY | default "payment-manager"}}'
    cmds:
      - docker build -t {{.REPOSITORY}}:{{.TAG}} .