version: '3'

includes:
  backend:
    taskfile: backend/Taskfile.yml
    dir: backend

tasks:
  environment:check:
    deps:
      - task: backend:environment:check

  build:
    deps:
      - task: backend:build