/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreatePaymentSourceResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreatePaymentSourceEndpointRequest, serializeCreatePaymentSourceResponse, type CreatePaymentSourceEndpointRequest, type CreatePaymentSourceResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { PaymentsourceItemRequestBuilderRequestsMetadata, type PaymentsourceItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/paymentsource
 */
export interface PaymentsourceRequestBuilder extends BaseRequestBuilder<PaymentsourceRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.paymentsource.item collection
     * @param id Unique identifier of the item
     * @returns {PaymentsourceItemRequestBuilder}
     */
     byId(id: Guid) : PaymentsourceItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePaymentSourceResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreatePaymentSourceEndpointRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePaymentSourceResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePaymentSourceEndpointRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PaymentsourceRequestBuilderUriTemplate = "{+baseurl}/api/paymentsource";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PaymentsourceRequestBuilderNavigationMetadata: Record<Exclude<keyof PaymentsourceRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PaymentsourceItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PaymentsourceRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PaymentsourceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePaymentSourceResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePaymentSourceEndpointRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
