version: '3'

tasks:
  environment:check:
    preconditions:
      - sh: dotnet --version
        msg: "The .NET CLI is required"
    cmds:
      - echo "All backend tooling are installed"

  build:
    cmds:
      - dotnet build

  install-dependencies:
    cmds:
      - dotnet restore

  lint:
    cmds:
      - dotnet format --verify-no-changes

  lint:fix:
    cmds:
      - dotnet format

  test:
    cmds:
      - dotnet test

  test:unit:
    cmds:
      - dotnet test --filter "FullyQualifiedName~Unit"

  test:integration:
    cmds:
      - dotnet test --filter "FullyQualifiedName~Integration"

  api:run:
    dir: ./src/PaymentManager.WebApi
    cmds:
      - dotnet run

  run:
    deps:
      - api:run

  add-migration:
    dir: ./src/PaymentManager.Infrastructure
    preconditions:
      - sh: test -n "$MIGRATION_NAME"
        msg: "Please provide a name for the migration via the MIGRATION_NAME environment variable"
    cmds:
      - dotnet ef migrations add $MIGRATION_NAME

  update-database:
    dir: ./src/PaymentManager.Infrastructure
    cmds:
      - |
        CONNECTION=${CONNECTION:-"Data Source=PaymentManager.db"}
        dotnet ef database update --connection "$CONNECTION"