/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddPaymentSplitsResponseSplitDto } from './add-payment-splits-response-split-dto';


export interface AddPaymentSplitsResponse { 
    paymentId: string;
    effectiveDate: string;
    splits: Array<AddPaymentSplitsResponseSplitDto>;
}

