/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddPaymentValueResponseAmount } from './add-payment-value-response-amount';
import { CreatePaymentResponseSplitDto } from './create-payment-response-split-dto';
import { CreatePaymentResponseValueDto } from './create-payment-response-value-dto';


export interface CreatePaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentValueResponseAmount;
    initialAmount: AddPaymentValueResponseAmount;
    values: Array<CreatePaymentResponseValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<CreatePaymentResponseSplitDto>;
}

