/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePaymentResponseSplitVersionDto } from './create-payment-response-split-version-dto';
import { CreatePaymentResponseSplitDto } from './create-payment-response-split-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';
import { CreatePaymentResponseValueDto } from './create-payment-response-value-dto';


export interface CreatePaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    initialAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    values: Array<CreatePaymentResponseValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<CreatePaymentResponseSplitDto>;
    initialSplits: Array<CreatePaymentResponseSplitDto>;
    splitVersions: Array<CreatePaymentResponseSplitVersionDto>;
}

