/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserShareDto } from './user-share-dto';
import { CreatePaymentResponseSplitDto } from './create-payment-response-split-dto';
import { EffectivePaymentValueDto } from './effective-payment-value-dto';


export interface CreatePaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: any | null;
    initialAmount: any | null;
    values: Array<EffectivePaymentValueDto>;
    currency: string;
    frequency: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    userShare: UserShareDto;
    splits: Array<CreatePaymentResponseSplitDto>;
}

