/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePaymentResponseSplitVersionDtoSplitDto } from './create-payment-response-split-version-dto-split-dto';


export interface CreatePaymentResponseSplitVersionDto { 
    effectiveDate: string;
    splits: Array<CreatePaymentResponseSplitVersionDtoSplitDto>;
}

