/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddPaymentValueResponseAmount } from './add-payment-value-response-amount';


export interface GetAllPaymentsResponsePaymentDtoSplitDto { 
    personId: string;
    percentage: AddPaymentValueResponseAmount;
    value: AddPaymentValueResponseAmount;
}

