/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponseOccurrenceDto } from './get-payment-occurrences-response-occurrence-dto';
import { GetPaymentOccurrencesResponsePersonCommitmentDto } from './get-payment-occurrences-response-person-commitment-dto';
import { GetPaymentOccurrencesResponseGroupSummaryDto } from './get-payment-occurrences-response-group-summary-dto';


export interface GetPaymentOccurrencesResponse { 
    occurrences: Array<GetPaymentOccurrencesResponseOccurrenceDto>;
    summary: Array<GetPaymentOccurrencesResponseGroupSummaryDto>;
    people: Array<GetPaymentOccurrencesResponsePersonCommitmentDto>;
}

