/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponseOccurrenceDtoSplitDto } from './get-payment-occurrences-response-occurrence-dto-split-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface GetPaymentOccurrencesResponseOccurrenceDto { 
    paymentId: string;
    paymentSourceId: string;
    payeeId: string;
    amount: AddPaymentSplitsResponseSplitDtoPercentage;
    currency: string;
    frequency: number;
    direction: number;
    occurrenceDate: string;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<GetPaymentOccurrencesResponseOccurrenceDtoSplitDto>;
}

