/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponsePaymentSourceBreakdownDto } from './get-payment-occurrences-response-payment-source-breakdown-dto';
import { GetPaymentOccurrencesResponseContactAmountDto } from './get-payment-occurrences-response-contact-amount-dto';


export interface GetPaymentOccurrencesResponseSummaryDto { 
    currency: string;
    totalAmount: any | null;
    userTotal: any | null;
    contactTotals: Array<GetPaymentOccurrencesResponseContactAmountDto>;
    byPaymentSource: Array<GetPaymentOccurrencesResponsePaymentSourceBreakdownDto>;
}

