/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPeopleResponsePersonDto } from './get-all-people-response-person-dto';


export interface GetAllPeopleResponse { 
    people: Array<GetAllPeopleResponsePersonDto>;
}

