/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponseOccurrenceDtoSplitDto } from './get-payment-occurrences-response-occurrence-dto-split-dto';
import { AddPaymentValueResponseAmount } from './add-payment-value-response-amount';


export interface GetPaymentOccurrencesResponseOccurrenceDto { 
    paymentId: string;
    paymentSourceId: string;
    payeeId: string;
    amount: AddPaymentValueResponseAmount;
    currency: string;
    frequency: number;
    direction: number;
    occurrenceDate: string;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<GetPaymentOccurrencesResponseOccurrenceDtoSplitDto>;
}

