/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPaymentsResponsePaymentDtoSplitDto } from './get-all-payments-response-payment-dto-split-dto';
import { UserShareDto } from './user-share-dto';


export interface GetAllPaymentsResponsePaymentDto { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    amount: any | null;
    currency: string;
    frequency: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    userShare: UserShareDto;
    splits: Array<GetAllPaymentsResponsePaymentDtoSplitDto>;
}

