/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponseCurrencySummaryDto } from './get-payment-occurrences-response-currency-summary-dto';


export interface GetPaymentOccurrencesResponseGroupSummaryDto { 
    payerGroupId: string;
    currencies: Array<GetPaymentOccurrencesResponseCurrencySummaryDto>;
}

