/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllUsersResponseUserDto } from './get-all-users-response-user-dto';


export interface GetAllUsersResponse { 
    users: Array<GetAllUsersResponseUserDto>;
}

