/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponseOccurrenceDto } from './get-payment-occurrences-response-occurrence-dto';


export interface GetPaymentOccurrencesResponse { 
    occurrences: Array<GetPaymentOccurrencesResponseOccurrenceDto>;
}

