/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPaymentsResponsePaymentDto } from './get-all-payments-response-payment-dto';


export interface GetAllPaymentsResponse { 
    payments: Array<GetAllPaymentsResponsePaymentDto>;
}

