/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponsePersonAmountDto } from './get-payment-occurrences-response-person-amount-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface GetPaymentOccurrencesResponseNetTotalsDto { 
    totalAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    personTotals: Array<GetPaymentOccurrencesResponsePersonAmountDto>;
}

