/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPayerGroupsResponsePayerGroupDto } from './get-all-payer-groups-response-payer-group-dto';


export interface GetAllPayerGroupsResponse { 
    payerGroups: Array<GetAllPayerGroupsResponsePayerGroupDto>;
}

