/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPaymentSourcesResponsePaymentSourceDto } from './get-all-payment-sources-response-payment-source-dto';


export interface GetAllPaymentSourcesResponse { 
    paymentSources: Array<GetAllPaymentSourcesResponsePaymentSourceDto>;
}

