/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentResponseValueDto } from './get-payment-response-value-dto';
import { GetPaymentResponseSplitDto } from './get-payment-response-split-dto';
import { GetPaymentResponseSplitVersionDto } from './get-payment-response-split-version-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface GetPaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    initialAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    values: Array<GetPaymentResponseValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<GetPaymentResponseSplitDto>;
    initialSplits: Array<GetPaymentResponseSplitDto>;
    splitVersions: Array<GetPaymentResponseSplitVersionDto>;
}

