/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPaymentsResponsePaymentDtoSplitVersionDtoSplitDto } from './get-all-payments-response-payment-dto-split-version-dto-split-dto';


export interface GetAllPaymentsResponsePaymentDtoSplitVersionDto { 
    effectiveDate: string;
    splits: Array<GetAllPaymentsResponsePaymentDtoSplitVersionDtoSplitDto>;
}

