/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPaymentsResponsePaymentDtoValueDto } from './get-all-payments-response-payment-dto-value-dto';
import { GetAllPaymentsResponsePaymentDtoSplitDto } from './get-all-payments-response-payment-dto-split-dto';
import { GetAllPaymentsResponsePaymentDtoSplitVersionDto } from './get-all-payments-response-payment-dto-split-version-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface GetAllPaymentsResponsePaymentDto { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    initialAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    values: Array<GetAllPaymentsResponsePaymentDtoValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<GetAllPaymentsResponsePaymentDtoSplitDto>;
    initialSplits: Array<GetAllPaymentsResponsePaymentDtoSplitDto>;
    splitVersions: Array<GetAllPaymentsResponsePaymentDtoSplitVersionDto>;
}

