/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponsePaymentSourceBreakdownDto } from './get-payment-occurrences-response-payment-source-breakdown-dto';
import { GetPaymentOccurrencesResponsePersonAmountDto } from './get-payment-occurrences-response-person-amount-dto';
import { AddPaymentValueResponseAmount } from './add-payment-value-response-amount';


export interface GetPaymentOccurrencesResponseDirectionTotalsDto { 
    totalAmount: AddPaymentValueResponseAmount;
    personTotals: Array<GetPaymentOccurrencesResponsePersonAmountDto>;
    byPaymentSource: Array<GetPaymentOccurrencesResponsePaymentSourceBreakdownDto>;
}

