/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllContactsResponseContactDto } from './get-all-contacts-response-contact-dto';


export interface GetAllContactsResponse { 
    contacts: Array<GetAllContactsResponseContactDto>;
}

