/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAllPayeesResponsePayeeDto } from './get-all-payees-response-payee-dto';


export interface GetAllPayeesResponse { 
    payees: Array<GetAllPayeesResponsePayeeDto>;
}

