/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentOccurrencesResponsePayeeAmountDto } from './get-payment-occurrences-response-payee-amount-dto';
import { GetPaymentOccurrencesResponseNetTotalsDto } from './get-payment-occurrences-response-net-totals-dto';
import { GetPaymentOccurrencesResponseDirectionTotalsDto } from './get-payment-occurrences-response-direction-totals-dto';


export interface GetPaymentOccurrencesResponseCurrencySummaryDto { 
    currency: string;
    outgoing: GetPaymentOccurrencesResponseDirectionTotalsDto;
    incoming: GetPaymentOccurrencesResponseDirectionTotalsDto;
    net: GetPaymentOccurrencesResponseNetTotalsDto;
    outgoingByPayee: Array<GetPaymentOccurrencesResponsePayeeAmountDto>;
}

