/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPaymentResponseSplitVersionDtoSplitDto } from './get-payment-response-split-version-dto-split-dto';


export interface GetPaymentResponseSplitVersionDto { 
    effectiveDate: string;
    splits: Array<GetPaymentResponseSplitVersionDtoSplitDto>;
}

