/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface GetPaymentOccurrencesResponsePersonCommitmentDto { 
    personId: string;
    currency: string;
    income: AddPaymentSplitsResponseSplitDtoPercentage;
    committed: AddPaymentSplitsResponseSplitDtoPercentage;
    remaining: AddPaymentSplitsResponseSplitDtoPercentage;
    isOverCommitted: boolean;
}

