/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentEndpointsUpdateRequest { 
    paymentSourceId: string;
    payeeId: string;
    amount: any | null;
    currency: string;
    frequency: number;
    startDate: string;
    endDate: string | null;
    description?: string | null;
}

