/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentEndpointsSplitRequest } from './payment-endpoints-split-request';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface PaymentEndpointsCreateRequest { 
    paymentSourceId: string;
    payeeId: string;
    amount: AddPaymentSplitsResponseSplitDtoPercentage;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description?: string | null;
    payerGroupId?: string | null;
    splits?: Array<PaymentEndpointsSplitRequest> | null;
}

