/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentEndpointsSplitRequest } from './payment-endpoints-split-request';


export interface PaymentEndpointsUpdateRequest { 
    paymentSourceId: string;
    payeeId: string;
    initialAmount: number;
    currency: string;
    frequency: number;
    startDate: string;
    endDate: string | null;
    description?: string | null;
    splits?: Array<PaymentEndpointsSplitRequest> | null;
}

