/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatus } from './problem-details-status';


export interface ProblemDetails { 
    type?: string | null;
    title?: string | null;
    status?: ProblemDetailsStatus | null;
    detail?: string | null;
    instance?: string | null;
}

