/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatePaymentResponseSplitVersionDto } from './update-payment-response-split-version-dto';
import { UpdatePaymentResponseSplitDto } from './update-payment-response-split-dto';
import { UpdatePaymentResponseValueDto } from './update-payment-response-value-dto';
import { AddPaymentSplitsResponseSplitDtoPercentage } from './add-payment-splits-response-split-dto-percentage';


export interface UpdatePaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    initialAmount: AddPaymentSplitsResponseSplitDtoPercentage;
    values: Array<UpdatePaymentResponseValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<UpdatePaymentResponseSplitDto>;
    initialSplits: Array<UpdatePaymentResponseSplitDto>;
    splitVersions: Array<UpdatePaymentResponseSplitVersionDto>;
}

