/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatePaymentResponseSplitVersionDtoSplitDto } from './update-payment-response-split-version-dto-split-dto';


export interface UpdatePaymentResponseSplitVersionDto { 
    effectiveDate: string;
    splits: Array<UpdatePaymentResponseSplitVersionDtoSplitDto>;
}

