/**
 * PaymentManager.WebApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatePaymentResponseSplitDto } from './update-payment-response-split-dto';
import { AddPaymentValueResponseAmount } from './add-payment-value-response-amount';
import { UpdatePaymentResponseValueDto } from './update-payment-response-value-dto';


export interface UpdatePaymentResponse { 
    id: string;
    userId: string;
    paymentSourceId: string;
    payeeId: string;
    currentAmount: AddPaymentValueResponseAmount;
    initialAmount: AddPaymentValueResponseAmount;
    values: Array<UpdatePaymentResponseValueDto>;
    currency: string;
    frequency: number;
    direction: number;
    startDate: string;
    endDate: string | null;
    description: string | null;
    payerGroupId: string | null;
    splits: Array<UpdatePaymentResponseSplitDto>;
}

