/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SourceRequestBuilderNavigationMetadata, SourceRequestBuilderRequestsMetadata, type SourceRequestBuilder } from './source/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payment
 */
export interface PaymentRequestBuilder extends BaseRequestBuilder<PaymentRequestBuilder> {
    /**
     * The source property
     */
    get source(): SourceRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PaymentRequestBuilderUriTemplate = "{+baseurl}/api/payment";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PaymentRequestBuilderNavigationMetadata: Record<Exclude<keyof PaymentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    source: {
        requestsMetadata: SourceRequestBuilderRequestsMetadata,
        navigationMetadata: SourceRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
