/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetPaymentOccurencesResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type GetPaymentOccurencesResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payments/occurrences
 */
export interface OccurrencesRequestBuilder extends BaseRequestBuilder<OccurrencesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetPaymentOccurencesResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<OccurrencesRequestBuilderGetQueryParameters> | undefined) : Promise<GetPaymentOccurencesResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OccurrencesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface OccurrencesRequestBuilderGetQueryParameters {
    from?: string;
    to?: string;
}
/**
 * Uri template for the request builder.
 */
export const OccurrencesRequestBuilderUriTemplate = "{+baseurl}/api/payments/occurrences{?from*,to*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const OccurrencesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OccurrencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetPaymentOccurencesResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
