import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

// Aspire injects service endpoints as: services__{resourceName}__{endpointName}__{index}={uri}
// Prefer HTTP to avoid self-signed certificate issues in local development.
const apiBaseUrl =
  process.env['services__web-api__http__0'] ??
  process.env['services__web-api__https__0'] ??
  'http://localhost:5001';

console.log(`→ API base URL: ${apiBaseUrl}`);

const envContent = `// Generated by scripts/aspire-start.ts — do not commit.
export const environment = {
  production: false,
  apiBaseUrl: '${apiBaseUrl}'
};
`;

const envFile = resolve(projectRoot, 'src/environments/environment.aspire.ts');
writeFileSync(envFile, envContent, 'utf-8');
console.log(`✔ Written: ${envFile}`);
