/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetPaymentSourceResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type GetPaymentSourceResponse, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payments/sources/{id}
 */
export interface SourcesItemRequestBuilder extends BaseRequestBuilder<SourcesItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetPaymentSourceResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetPaymentSourceResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SourcesItemRequestBuilderUriTemplate = "{+baseurl}/api/payments/sources/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const SourcesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SourcesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetPaymentSourceResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
