/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateUser}
 */
// @ts-ignore
export function createCreateUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateUser;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Response}
 */
// @ts-ignore
export function createResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResponse;
}
export interface CreateUser extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateUser(createUser: Partial<CreateUser> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createUser.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResponse(response: Partial<Response> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { response.id = n.getGuidValue(); },
        "name": n => { response.name = n.getStringValue(); },
    }
}
export interface Response extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateUser(writer: SerializationWriter, createUser: Partial<CreateUser> | undefined | null = {}) : void {
    if (createUser) {
        writer.writeStringValue("name", createUser.name);
        writer.writeAdditionalData(createUser.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResponse(writer: SerializationWriter, response: Partial<Response> | undefined | null = {}) : void {
    if (response) {
        writer.writeGuidValue("id", response.id);
        writer.writeStringValue("name", response.name);
        writer.writeAdditionalData(response.additionalData);
    }
}
/* tslint:enable */
/* eslint-enable */
