/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OccurrencesRequestBuilderRequestsMetadata, type OccurrencesRequestBuilder } from './occurrences/index.js';
// @ts-ignore
import { SourceRequestBuilderRequestsMetadata, type SourceRequestBuilder } from './source/index.js';
// @ts-ignore
import { SourcesRequestBuilderNavigationMetadata, SourcesRequestBuilderRequestsMetadata, type SourcesRequestBuilder } from './sources/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payments
 */
export interface PaymentsRequestBuilder extends BaseRequestBuilder<PaymentsRequestBuilder> {
    /**
     * The occurrences property
     */
    get occurrences(): OccurrencesRequestBuilder;
    /**
     * The source property
     */
    get source(): SourceRequestBuilder;
    /**
     * The sources property
     */
    get sources(): SourcesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PaymentsRequestBuilderUriTemplate = "{+baseurl}/api/payments";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PaymentsRequestBuilderNavigationMetadata: Record<Exclude<keyof PaymentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    occurrences: {
        requestsMetadata: OccurrencesRequestBuilderRequestsMetadata,
    },
    source: {
        requestsMetadata: SourceRequestBuilderRequestsMetadata,
    },
    sources: {
        requestsMetadata: SourcesRequestBuilderRequestsMetadata,
        navigationMetadata: SourcesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
