namespace PaymentManager.WebApi;

/// <summary>
/// Marker type used as <c>TEntryPoint</c> for <c>WebApplicationFactory&lt;TestEntry&gt;</c>
/// in integration tests. Provides an unambiguous reference into the WebApi assembly without
/// conflicting with the global-namespace <c>Program</c> generated by top-level statements.
/// </summary>
public sealed class TestEntry;
