/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreatePaymentSourceResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreatePaymentSourceEndpointRequest, serializeCreatePaymentSourceResponse, type CreatePaymentSourceEndpointRequest, type CreatePaymentSourceResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payments/source
 */
export interface SourceRequestBuilder extends BaseRequestBuilder<SourceRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePaymentSourceResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreatePaymentSourceEndpointRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePaymentSourceResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePaymentSourceEndpointRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SourceRequestBuilderUriTemplate = "{+baseurl}/api/payments/source";
/**
 * Metadata for all the requests in the request builder.
 */
export const SourceRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SourceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePaymentSourceResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePaymentSourceEndpointRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
