name: Application

on:
  - pull_request

permissions:
  contents: read

env:
  tag: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dev container CLI
        run: npm install -g @devcontainers/cli
      - name: Spin up dev container
        run: devcontainer up --workspace-folder . --remote-env LOCKED_DEPS=true
      - name: Install tools
        run: devcontainer exec --workspace-folder . -- task install-tools
      - name: Install dependencies
        run: devcontainer exec --workspace-folder . -- task backend:install-locked-dependencies
      - name: Build
        run: devcontainer exec --workspace-folder . -- task backend:build
      - name: Lint
        run: devcontainer exec --workspace-folder . -- task backend:lint
      - name: Unit Test
        run: devcontainer exec --workspace-folder . -- task backend:test:unit
      - name: Integration Test
        run: devcontainer exec --workspace-folder . -- task backend:test:integration

  frontend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dev container CLI
        run: npm install -g @devcontainers/cli
      - name: Spin up dev container
        run: devcontainer up --workspace-folder . --remote-env LOCKED_DEPS=true
      - name: Install dependencies
        run: devcontainer exec --workspace-folder . -- task frontend:install-locked-dependencies
      - name: Build
        run: devcontainer exec --workspace-folder . -- task frontend:build
      - name: Lint
        run: devcontainer exec --workspace-folder . -- task frontend:lint