name: Release

on:
  push:
    tags:
      - '*'

env:
  TAG: ${GITHUB_REF_NAME}
  REPOSITORY: ghcr.io/${GITHUB_REPOSITORY}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Build Docker image
        run: task image:build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker push ${{ env.REPOSITORY }}:${{ env.TAG }}
          docker push ${{ env.REPOSITORY }}:latest
